name: 'Deploy'
on:
  push:
    branches:
      - master
jobs:
    build:

      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [13.x]

      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js
          uses: actions/setup-node@v1
          with:
            node-version: '12.x'
        - name: Install dependencies
          run: npm ci
        - name: Build
          run: npm run predeploy
        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./build